### ISSUE TITLE
Extension page - Fatal error

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#36]
A fatal error is generated when accessing the extensions page when no addon is activated.

**Fatal error:** Uncaught Error: Call to undefined method WP_Error::get_items() in /var/www/clients/client1/web58/web/wp-content/plugins/fakturo/includes/addons_page.php:132 Stack trace: #0 /var/www/clients/client1/web58/web/wp-content/plugins/fakturo/includes/addons_page.php(99): fktr_admin_page::read_addons() #1 /var/www/clients/client1/web58/web/wp-includes/class-wp-hook.php(310): fktr_admin_page::showhide_addons() #2 /var/www/clients/client1/web58/web/wp-includes/plugin.php(205): WP_Hook->apply_filters() #3 /var/www/clients/client1/web58/web/wp-admin/includes/class-wp-plugins-list-table.php(104): apply_filters() #4 /var/www/clients/client1/web58/web/wp-admin/plugins.php(534): WP_Plugins_List_Table->prepare_items() #5 /var/www/clients/client1/web58/web/wp-content/plugins/fakturo/includes/addons_page.php(92): require('...') #6 /var/www/clients/client1/web58/web/wp-includes/class-wp-hook.php(310): fktr_admin_page::plugins_page() #7 /var/www/clients/client1/web58/web/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters() #8 /var/www/clients/client1/web58/web/wp-includes/plugin.php(517): WP_Hook->do_action() #9 /var/www/clients/client1/web58/web/wp-admin/admin.php(259): do_action() #10 /var/www/clients/client1/web58/web/wp-admin/plugins.php(10): require_once('...') #11 {main} thrown in /var/www/clients/client1/web58/web/wp-content/plugins/fakturo/includes/addons_page.php on line 132

**Comment by manuelge** [comment]
Fixed
