### ISSUE TITLE
Fatal error on See PDF button

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#40]
A fatal error is generated when clicking on the "See PDF" button on the template creation screen.
<img width="1740" alt="image" src="https://github.com/etruel/fakturo/assets/31927829/b749f4ff-148c-4bfe-ab2f-f672085ee1df">

PHP Fatal error:  Uncaught Error: Class "Dompdf\Dompdf" not found in /var/www/clients/client1/web58/web/wp-content/plugins/fakturo/includes/libs/fktr_pdf.php:13
Stack trace:
#0 /var/www/clients/client1/web58/web/wp-content/plugins/fakturo/includes/post-types-print-templates.php(416): fktr_pdf::getInstance()
#1 /var/www/clients/client1/web58/web/wp-includes/class-wp-hook.php(324): fktrPostTypePrintTemplates::show_print_template()
#2 /var/www/clients/client1/web58/web/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /var/www/clients/client1/web58/web/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /var/www/clients/client1/web58/web/wp-admin/admin-post.php(85): do_action()
#5 {main}
  thrown in /var/www/clients/client1/web58/web/wp-content/plugins/fakturo/includes/libs/fktr_pdf.php on line 13

**Comment by manuelge** [comment]
The same error is generated in the Reports>Products screen when clicking on the PDF button.
